config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#new'

  post   '/users', to: 'users#create'
  get    '/users/:id', to: 'users#show', as: 'user'
  get    '/users/:id', to: 'users#destroy', as: 'destroy'
  patch  '/users/:id', to: 'users#update'

  get    '/login', to: 'sessions#create'
  get    '/logout', to: 'sessions#destroy'

  post   '/beers', to: 'beers#create', as: 'beer_create'
  get    '/beers', to: 'beers#index', as: 'beers'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/beer.rb
class Beer < ApplicationRecord

	has_many :ratings, dependent: :destroy

	ratyrate_rateable 'score'

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :ratings, dependent: :destroy
	has_secure_password

	ratyrate_rater
	# validates :name, presence: true
  # validates :password, presence: true
	# validates :email, presence: true

	validates :email, uniqueness: true
  	validates :password, presence: true
	# validates :name length: { minimum: 1, maximum: 200 }
	# validates :email length: { minimum: 1, maximum: 200 }
	# validates :password length: { minimum: 1, maximum: 200 }
	# validates :birthday length: { minimum: 1, maximum: 200 }


	# has_many :ratings, dependent: :destroy

	def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user ? @user.authenticate(params[:password]) : false
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

	def index
		@q = Beer.ransack(params[:q])
		@beers = @q.result(distinct: true)
 		@beer = Beer.new
  end

	def create
	  @beer = Beer.new(validate_beer)
	  if @beer.save
		  redirect_to '/beers'
	  end
	end

	private

	def validate_beer
    	params.require(:beer).permit(:name, :style, :brewery, :country, :ibu, :abv, :image)
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if current_user
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
  	user_params = params.require(:user).permit(:email, :password)
  	@user = User.confirm(user_params)
  	if(@user)
  		login(@user)
  		redirect_to @user
  	else
  		redirect_to root_path
    end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
  		login(@user)
      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end

  def update
    @user = User.find_by_id(session[:user_id])
    @user.update_attributes(user_params)
    redirect_to user_path(@user)
  end

  def new
    @user = User.new
  end

  def show
    id = params[:id]
    @user = User.find_by_id(id)
    @beers = Beer.all
  end

  private

  def user_params
    params.require(:user).permit(:email,:name,:password,:birthday)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/beers_helper.rb
module BeersHelper

end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
		session[:user_id] = user.id
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_id(session[:user_id])
	end

	def logout
		# @current_user = session[:id] = nil
		redirect_to root_path
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beers/index.html.erb
<%= render "shared/nav" %>
<!-- <%= render "shared/search_nav" %> -->
<h2 class="header">Search for a Beer! Can't find it? Then add it!</h2>
<div class="main">
  <div class="container">
    <div class="col s12 m7">
      <%= render "shared/search_nav" %>
      <%= render "shared/add_beer" %>
      <% @beers.each do |b| %>
      <div class="card horizontal">
        <div class="card-image">
          <%= image_tag(b.image, :class => "beer_image") %>
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <h2><%= b.name%></h2>
            <h5>Brewed by: <%= b.brewery%></h5>
            <p>Style: <%= b.style%></p>
            <p><%= b.ibu%> IBUs <%= b.abv%>% ABV</p>
            <p><%= b.country%></p>
            <div class="small-2 large-4 columns">
              <% if current_user %>
                Growlr Score: <%= rating_for b, "score", disable_after_rate: false %>
                Your Score: <%= rating_for_user b, current_user, "score", stars: 10, disable_after_rate: false  %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeerApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'beer.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Lobster|Raleway" rel="stylesheet">
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/shared/_add_beer.html.erb
<a class="waves-effect waves-light btn modal-trigger add" href="#modal3">Add a Beer</a>

<div id="modal3" class="modal">
  <div class="modal-content">
    <%= form_for @beer, :id=>"beer-form", :class=> "col s12" do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :name %>
        <%= f.label :name %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :brewery %>
        <%= f.label :brewery %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :style %>
        <%= f.label :style %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :country %>
        <%= f.label :country %>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <div class="input-field inline">
          <%= f.text_field :ibu %>
          <%= f.label :ibu %>
        </div>
        <div class="input-field inline">
          <%= f.text_field :abv %>
          <%= f.label :abv %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :image %>
        <%= f.label :image %>
      </div>
    </div>
    <div class="row">
      <div class="modal-footer">
        <%= f.submit "submit", :class=> "btn-flat" %>
      </div>
    </div>

    <% end %>
  </div>
</div>

app/views/shared/_edit.html.erb
<a class="waves-effect waves-light btn modal-trigger dude" href="#modal3">Edit Profile</a>

<div id="modal3" class="modal sick">
  <div class="modal-content">
    <%= form_for @user, :class=> "col s12" do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :name %>
        <%= f.label :name, :class=> "active" %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
       <%= f.text_field :email %>
       <%= f.label :email, :class=> "active" %>
     </div>
   </div>
   <div class="row">
     <div class="input-field col s12">
       <%= f.text_field :password %>
       <%= f.label :password, :class=> "active" %>
     </div>
   </div>
   <div class="row">
     <div class="input-field col s12">
       <%= f.text_field :birthday %>
       <%= f.label :birthday, :class=> "active" %>
     </div>
   </div>
    <div class="modal-footer">
      <%= f.submit "submit", :class=> "btn-flat" %>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav>
  <div class="nav-wrapper">

    <a href="/beers" class="brand-logo left">Growlr</a>

    <ul id="nav-mobile" class="right">
      <%if current_page?("/beers")%>
        <li><%= link_to "Profile Page", user_path(current_user[:id]), class: "btn-flat" %></li>
      <%else%>
        <li><%= link_to "Search For Beers", beers_path, class: "btn-flat" %></li>
      <%end%>
      <li><%= link_to "Log Out", logout_path, class: "btn-flat" %></li>
    </ul>
  </div>
</nav>

app/views/shared/_search_nav.html.erb
  <div class="search">
    <%= search_form_for @q do |f| %>
        <%= f.label :search_by_name_or_style_or_brewery_or_country %>
        <%= f.search_field :name_or_style_or_brewery_or_country_cont, class:"input-field col s6"%>
      <%= f.submit "Search for a Beer!", class:"btn-flat"%>
    <% end %>
  </div>

app/views/shared/_sign_up_login_modal.html.erb
<!-- Sign Up Modal -->
<div id="modal_signup" class="modal modal-fixed-footer">
  <%= form_for @user do |f| %>
  <div class="modal-content">
    <div class="row">

      <!-- <form class="col s12"> -->
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name%>
          <label for="name">Enter First and Last Name</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :email%>
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.password_field :password%>
          <label for="password">Password</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :birthday%>
          <label for="birthday">Birthday</label>
        </div>
      </div>
      <!-- </form> -->
    </div>
  </div>
  <div class="modal-footer">
    <a class="modal-action modal-close waves-effect waves-red btn-flat">Cancel</a>
    <%= f.submit "Save", class: "btn-flat"%>
  </div>
  <%end%>
</div>

<!-- Signup Modal End-->

<!-- Login Modal -->
<div id="modal_login" class="modal modal-fixed-footer">
  <% @user=User.new %>
  <%= form_for @user, url: '/login', method: 'get' do |f| %>
  <div class="modal-content">


    <div class="row">
      <div class="input-field col s12">
        <%= f.email_field :email, placeholder: "Email" %>
        <label for="email">Email</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.password_field :password, placeholder: "Password" %>
        <label for="password">Password</label>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <a class="modal-action modal-close waves-effect waves-red btn-flat">Cancel</a>
    <%= f.submit "Login", class: "btn-flat" %>

    <!--  <a class="modal-action modal-close waves-effect waves-green btn-flat">Login</a> -->

  </div>
  <% end %>
</div>
<!-- Login Modal End-->

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s6 offset-s3 hello">
      <div class="section brand-logo">
        <h1> Growlr</h1>
        <h3>No Crap On Tap!</h3>
      </div>
      <div class="section">
        <!-- Signup Modal Button -->
        <a class="waves-effect waves-light btn modal-trigger" href="#modal_signup">Sign Up!</a>
        <!-- Login Modal Button -->
        <a class="waves-effect waves-light btn modal-trigger" href="#modal_login">Login</a>
      </div>
    </div>
  </div>
</div>

<%= render "shared/sign_up_login_modal" %>

<div class="container">
  <div class="row">
    <div class="col s12 hello">
      <div class="section brand-logo">
        <h1> Welcome to Growlr!</h1>
        <h4>  &emsp; Growlr is your personal beer assistant.
          A place for you to keep track of your favorite beers,
          rate beers you've tried, and discover new beers. Tired
          of going out with your friends and finding your new
          favorite beer, only to drink too many of them and forget
          what they were called? That's when Growlr comes in. With
          just a few clicks, you can add a rating to a beer and it
          will be added to your list so you'll always be able to find it.</h4>

        <h4>&emsp; Because Growler is about beer, you do need to be over 21 years
          of age to sign up. So if you were not born before 21 years ago from right now
          (E.G. Your birthday is after: <%= 21.years.ago.to_formatted_s(:long_ordinal) %>)
          this site is not for you! </h4>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/nav" %>

<div class="profile">
  <h1>Hey <%= @user.name %>!</h1>
  <h3>Email: <%= @user.email %></h3>
  <h3>Birthday: <%= @user.birthday %></h3>
</div>

<%= render "shared/edit" %>
<div class="main">
  <div class="container">
    <div class="col s12 m7">
      <% @beers.each do |b| %>
      <div class="card horizontal">
        <div class="card-image">
          <%= image_tag(b.image, :class => "beer_image") %>
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <h2><%= b.name%></h2>
            <h5>Brewed by: <%= b.brewery%></h5>
            <p>Style: <%= b.style%></p>
            <p><%= b.ibu%> IBUs <%= b.abv%>% ABV</p>
            <p><%= b.country%></p>
            <div class="small-2 large-4 columns">
              <% if current_user %>
                Growlr Score: <%= rating_for b, "score", disable_after_rate: false %>
                Your Score: <%= rating_for_user b, current_user, "score", stars: 10, disable_after_rate: false  %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>